"""Countries for the country picker: display name, ISO 3166 alpha-2 code and search aliases.

Generated from pycountry. Aliases cover common alternative names and earlier stored names."""

COUNTRY_DATA = [
    ('Afghanistan', 'AF', ()),
    ('Albania', 'AL', ()),
    ('Algeria', 'DZ', ()),
    ('American Samoa', 'AS', ()),
    ('Andorra', 'AD', ()),
    ('Angola', 'AO', ()),
    ('Anguilla', 'AI', ()),
    ('Antarctica', 'AQ', ()),
    ('Antigua and Barbuda', 'AG', ()),
    ('Argentina', 'AR', ()),
    ('Armenia', 'AM', ()),
    ('Aruba', 'AW', ()),
    ('Australia', 'AU', ()),
    ('Austria', 'AT', ()),
    ('Azerbaijan', 'AZ', ()),
    ('Bahamas', 'BS', ()),
    ('Bahrain', 'BH', ()),
    ('Bangladesh', 'BD', ()),
    ('Barbados', 'BB', ()),
    ('Belarus', 'BY', ()),
    ('Belgium', 'BE', ()),
    ('Belize', 'BZ', ()),
    ('Benin', 'BJ', ()),
    ('Bermuda', 'BM', ()),
    ('Bhutan', 'BT', ()),
    ('Bolivia', 'BO', ('Plurinational State of Bolivia',)),
    ('Bonaire, Sint Eustatius and Saba', 'BQ', ()),
    ('Bosnia and Herzegovina', 'BA', ('Bosnia',)),
    ('Botswana', 'BW', ()),
    ('Bouvet Island', 'BV', ()),
    ('Brazil', 'BR', ()),
    ('British Indian Ocean Territory', 'IO', ()),
    ('British Virgin Islands', 'VG', ('Virgin Islands, British',)),
    ('Brunei Darussalam', 'BN', ()),
    ('Bulgaria', 'BG', ()),
    ('Burkina Faso', 'BF', ()),
    ('Burundi', 'BI', ()),
    ('Cabo Verde', 'CV', ('Cape Verde',)),
    ('Cambodia', 'KH', ()),
    ('Cameroon', 'CM', ()),
    ('Canada', 'CA', ()),
    ('Cayman Islands', 'KY', ()),
    ('Central African Republic', 'CF', ()),
    ('Chad', 'TD', ()),
    ('Chile', 'CL', ()),
    ('China', 'CN', ()),
    ('Christmas Island', 'CX', ()),
    ('Cocos (Keeling) Islands', 'CC', ()),
    ('Colombia', 'CO', ()),
    ('Comoros', 'KM', ()),
    ('Congo', 'CG', ('Republic of the Congo', 'Congo-Brazzaville')),
    ('Cook Islands', 'CK', ()),
    ('Costa Rica', 'CR', ()),
    ('Croatia', 'HR', ()),
    ('Cuba', 'CU', ()),
    ('Curaçao', 'CW', ()),
    ('Cyprus', 'CY', ()),
    ('Czechia', 'CZ', ('Czech Republic',)),
    ("Côte d'Ivoire", 'CI', ('Ivory Coast',)),
    ('Democratic Republic of the Congo', 'CD', ('DR Congo', 'DRC', 'Congo-Kinshasa', 'Congo, The Democratic Republic of the')),
    ('Denmark', 'DK', ()),
    ('Djibouti', 'DJ', ()),
    ('Dominica', 'DM', ()),
    ('Dominican Republic', 'DO', ()),
    ('Ecuador', 'EC', ()),
    ('Egypt', 'EG', ()),
    ('El Salvador', 'SV', ()),
    ('Equatorial Guinea', 'GQ', ()),
    ('Eritrea', 'ER', ()),
    ('Estonia', 'EE', ()),
    ('Eswatini', 'SZ', ('Swaziland',)),
    ('Ethiopia', 'ET', ()),
    ('Falkland Islands (Malvinas)', 'FK', ()),
    ('Faroe Islands', 'FO', ()),
    ('Fiji', 'FJ', ()),
    ('Finland', 'FI', ()),
    ('France', 'FR', ()),
    ('French Guiana', 'GF', ()),
    ('French Polynesia', 'PF', ()),
    ('French Southern Territories', 'TF', ()),
    ('Gabon', 'GA', ()),
    ('Gambia', 'GM', ()),
    ('Georgia', 'GE', ()),
    ('Germany', 'DE', ()),
    ('Ghana', 'GH', ()),
    ('Gibraltar', 'GI', ()),
    ('Greece', 'GR', ()),
    ('Greenland', 'GL', ()),
    ('Grenada', 'GD', ()),
    ('Guadeloupe', 'GP', ()),
    ('Guam', 'GU', ()),
    ('Guatemala', 'GT', ()),
    ('Guernsey', 'GG', ()),
    ('Guinea', 'GN', ()),
    ('Guinea-Bissau', 'GW', ()),
    ('Guyana', 'GY', ()),
    ('Haiti', 'HT', ()),
    ('Heard Island and McDonald Islands', 'HM', ()),
    ('Honduras', 'HN', ()),
    ('Hong Kong', 'HK', ()),
    ('Hungary', 'HU', ()),
    ('Iceland', 'IS', ()),
    ('India', 'IN', ()),
    ('Indonesia', 'ID', ()),
    ('Iran', 'IR', ('Persia',)),
    ('Iraq', 'IQ', ()),
    ('Ireland', 'IE', ()),
    ('Isle of Man', 'IM', ()),
    ('Israel', 'IL', ()),
    ('Italy', 'IT', ()),
    ('Jamaica', 'JM', ()),
    ('Japan', 'JP', ()),
    ('Jersey', 'JE', ()),
    ('Jordan', 'JO', ()),
    ('Kazakhstan', 'KZ', ()),
    ('Kenya', 'KE', ()),
    ('Kiribati', 'KI', ()),
    ('Kosovo', 'XK', ()),
    ('Kuwait', 'KW', ()),
    ('Kyrgyzstan', 'KG', ()),
    ('Laos', 'LA', ('Lao PDR',)),
    ('Latvia', 'LV', ()),
    ('Lebanon', 'LB', ()),
    ('Lesotho', 'LS', ()),
    ('Liberia', 'LR', ()),
    ('Libya', 'LY', ()),
    ('Liechtenstein', 'LI', ()),
    ('Lithuania', 'LT', ()),
    ('Luxembourg', 'LU', ()),
    ('Macao', 'MO', ()),
    ('Madagascar', 'MG', ()),
    ('Malawi', 'MW', ()),
    ('Malaysia', 'MY', ()),
    ('Maldives', 'MV', ()),
    ('Mali', 'ML', ()),
    ('Malta', 'MT', ()),
    ('Marshall Islands', 'MH', ()),
    ('Martinique', 'MQ', ()),
    ('Mauritania', 'MR', ()),
    ('Mauritius', 'MU', ()),
    ('Mayotte', 'YT', ()),
    ('Mexico', 'MX', ()),
    ('Micronesia', 'FM', ('Micronesia, Federated States of',)),
    ('Moldova', 'MD', ()),
    ('Monaco', 'MC', ()),
    ('Mongolia', 'MN', ()),
    ('Montenegro', 'ME', ()),
    ('Montserrat', 'MS', ()),
    ('Morocco', 'MA', ()),
    ('Mozambique', 'MZ', ()),
    ('Myanmar', 'MM', ('Burma',)),
    ('Namibia', 'NA', ()),
    ('Nauru', 'NR', ()),
    ('Nepal', 'NP', ()),
    ('Netherlands', 'NL', ('Holland', 'The Netherlands')),
    ('New Caledonia', 'NC', ()),
    ('New Zealand', 'NZ', ()),
    ('Nicaragua', 'NI', ()),
    ('Niger', 'NE', ()),
    ('Nigeria', 'NG', ()),
    ('Niue', 'NU', ()),
    ('Norfolk Island', 'NF', ()),
    ('North Korea', 'KP', ('DPRK',)),
    ('North Macedonia', 'MK', ('Macedonia',)),
    ('Northern Mariana Islands', 'MP', ()),
    ('Norway', 'NO', ()),
    ('Oman', 'OM', ()),
    ('Pakistan', 'PK', ()),
    ('Palau', 'PW', ()),
    ('Palestine', 'PS', ('Palestine, State of',)),
    ('Panama', 'PA', ()),
    ('Papua New Guinea', 'PG', ()),
    ('Paraguay', 'PY', ()),
    ('Peru', 'PE', ()),
    ('Philippines', 'PH', ()),
    ('Pitcairn', 'PN', ()),
    ('Poland', 'PL', ()),
    ('Portugal', 'PT', ()),
    ('Puerto Rico', 'PR', ()),
    ('Qatar', 'QA', ()),
    ('Romania', 'RO', ()),
    ('Russian Federation', 'RU', ('Russia',)),
    ('Rwanda', 'RW', ()),
    ('Réunion', 'RE', ()),
    ('Saint Barthélemy', 'BL', ()),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH', ()),
    ('Saint Kitts and Nevis', 'KN', ()),
    ('Saint Lucia', 'LC', ()),
    ('Saint Martin (French part)', 'MF', ()),
    ('Saint Pierre and Miquelon', 'PM', ()),
    ('Saint Vincent and the Grenadines', 'VC', ()),
    ('Samoa', 'WS', ()),
    ('San Marino', 'SM', ()),
    ('Sao Tome and Principe', 'ST', ()),
    ('Saudi Arabia', 'SA', ()),
    ('Senegal', 'SN', ()),
    ('Serbia', 'RS', ()),
    ('Seychelles', 'SC', ()),
    ('Sierra Leone', 'SL', ()),
    ('Singapore', 'SG', ()),
    ('Sint Maarten (Dutch part)', 'SX', ()),
    ('Slovakia', 'SK', ()),
    ('Slovenia', 'SI', ()),
    ('Solomon Islands', 'SB', ()),
    ('Somalia', 'SO', ()),
    ('South Africa', 'ZA', ()),
    ('South Georgia and the South Sandwich Islands', 'GS', ()),
    ('South Korea', 'KR', ('Korea', 'Republic of Korea')),
    ('South Sudan', 'SS', ()),
    ('Spain', 'ES', ()),
    ('Sri Lanka', 'LK', ()),
    ('Sudan', 'SD', ()),
    ('Suriname', 'SR', ()),
    ('Svalbard and Jan Mayen', 'SJ', ()),
    ('Sweden', 'SE', ()),
    ('Switzerland', 'CH', ()),
    ('Syria', 'SY', ('Syrian Arab Republic',)),
    ('Taiwan', 'TW', ()),
    ('Tajikistan', 'TJ', ()),
    ('Tanzania', 'TZ', ()),
    ('Thailand', 'TH', ()),
    ('Timor-Leste', 'TL', ('East Timor',)),
    ('Togo', 'TG', ()),
    ('Tokelau', 'TK', ()),
    ('Tonga', 'TO', ()),
    ('Trinidad and Tobago', 'TT', ()),
    ('Tunisia', 'TN', ()),
    ('Turkmenistan', 'TM', ()),
    ('Turks and Caicos Islands', 'TC', ()),
    ('Tuvalu', 'TV', ()),
    ('Türkiye', 'TR', ('Turkey',)),
    ('US Virgin Islands', 'VI', ('Virgin Islands, U.S.',)),
    ('Uganda', 'UG', ()),
    ('Ukraine', 'UA', ()),
    ('United Arab Emirates', 'AE', ('UAE', 'Emirates')),
    ('United Kingdom', 'GB', ('UK', 'Great Britain', 'Britain', 'England', 'Scotland', 'Wales', 'Northern Ireland')),
    ('United States', 'US', ('USA', 'United States of America', 'America')),
    ('United States Minor Outlying Islands', 'UM', ()),
    ('Uruguay', 'UY', ()),
    ('Uzbekistan', 'UZ', ()),
    ('Vanuatu', 'VU', ()),
    ('Vatican City', 'VA', ('Vatican', 'Holy See', 'Holy See (Vatican City State)')),
    ('Venezuela', 'VE', ()),
    ('Vietnam', 'VN', ('Viet Nam',)),
    ('Wallis and Futuna', 'WF', ()),
    ('Western Sahara', 'EH', ()),
    ('Yemen', 'YE', ()),
    ('Zambia', 'ZM', ()),
    ('Zimbabwe', 'ZW', ()),
    ('Åland Islands', 'AX', ()),
]

COUNTRIES = [name for name, _, _ in COUNTRY_DATA]
COUNTRY_CODES = {name: code for name, code, _ in COUNTRY_DATA}


def flag_emoji(code):
    """Two regional indicator symbols render as the flag of an ISO alpha-2 code."""
    if not code or len(code) != 2 or not code.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in code.upper())
