"""Build the dashboard map files from Natural Earth (public domain).

    .venv/bin/python scripts/build_map.py

Downloads the admin 0 countries once and writes:
- static/img/world.svg: the land outline (110m), equirectangular, used as a CSS mask;
- countries_geo.py: each country's label point (50m) in the same map coordinates.
Run it again only to refresh the data. Standard library only.
"""
import json
import os
import urllib.request

BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIDTH = 1000
NORTH, SOUTH = 84, -58  # crop: no Antarctica, little empty Arctic
HEIGHT = round((NORTH - SOUTH) / 360 * WIDTH, 1)


# Places Natural Earth folds into another country (French overseas regions, Gibraltar...):
# (longitude, latitude) of their main town. The US Minor Outlying Islands are too scattered.
EXTRA = {"BQ": (-68.27, 12.15), "BV": (3.4, -54.42), "CC": (96.83, -12.19),
         "CX": (105.68, -10.45), "GF": (-53.13, 3.93), "GI": (-5.35, 36.14),
         "GP": (-61.55, 16.25), "MQ": (-61.02, 14.64), "RE": (55.53, -21.13),
         "SJ": (15.65, 78.22), "TK": (-171.85, -9.2), "YT": (45.17, -12.83)}


def fetch(name):
    with urllib.request.urlopen(BASE + name, timeout=60) as resp:
        return json.load(resp)


def project(lon, lat):
    lat = max(min(lat, NORTH), SOUTH)
    return (lon + 180) / 360 * WIDTH, (NORTH - lat) / 360 * WIDTH


def iso(props):
    for key in ("ISO_A2_EH", "ISO_A2"):
        code = props.get(key)
        if code and code != "-99":
            return code
    return None


def ring_path(ring):
    out, last = [], None
    for lon, lat in ring:
        x, y = project(lon, lat)
        point = (round(x, 1), round(y, 1))
        if point != last:
            out.append(point)
            last = point
    if len(out) < 3:
        return ""
    return "M" + "L".join(f"{x:g} {y:g}" for x, y in out) + "Z"


def outline(features):
    parts = []
    for f in features:
        if f["properties"].get("CONTINENT") == "Antarctica":
            continue
        geom = f["geometry"]
        polygons = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
        for polygon in polygons:
            for ring in polygon:
                parts.append(ring_path(ring))
    return "".join(parts)


def main():
    land = fetch("ne_110m_admin_0_countries.geojson")["features"]
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT:g}">'
           f'<path fill="#000" fill-rule="evenodd" d="{outline(land)}"/></svg>\n')
    with open(os.path.join(ROOT, "static", "img", "world.svg"), "w") as fh:
        fh.write(svg)

    points = {}
    for f in fetch("ne_50m_admin_0_countries.geojson")["features"]:
        p = f["properties"]
        code = iso(p)
        # Antarctica is cropped out of the map, so it gets no point.
        if code and code not in points and p.get("LABEL_X") is not None and p["LABEL_Y"] > SOUTH:
            x, y = project(p["LABEL_X"], p["LABEL_Y"])
            points[code] = (round(x / WIDTH * 100, 2), round(y / HEIGHT * 100, 2))
    for code, (lon, lat) in EXTRA.items():
        if code not in points:
            x, y = project(lon, lat)
            points[code] = (round(x / WIDTH * 100, 2), round(y / HEIGHT * 100, 2))
    lines = ['"""Where each country sits on the dashboard map, as (left %, top %) of the map.',
             "",
             "Generated by scripts/build_map.py from Natural Earth (public domain) label points.",
             'Do not edit by hand."""', "", "COUNTRY_POINTS = {"]
    lines += [f'    "{code}": {points[code]},' for code in sorted(points)]
    lines += ["}", ""]
    with open(os.path.join(ROOT, "countries_geo.py"), "w") as fh:
        fh.write("\n".join(lines))
    print(f"world.svg {len(svg) // 1024} KB, {len(points)} country points")


if __name__ == "__main__":
    main()
